### ISSUE TITLE
vai -ominaisuuden järkevöittäminen

### ISSUE THREAD

**Issue by rennehir** [matias-kovero/rooboot-bot#3]
Botti vastaanyt jokaiseen viestiin, jossa kuuluu sana `vai`. Välillä aika ärsyttävää kun pitkän viestin keskeltä löytyy sana ja botti toistaa toisen puoliskon.

Tuota voisi kokeilla korjata vaikka niin, että etsii muita välimerkkejä vai-sanojen välistä? Eli esim viesti: `Mitä kuuluu? Pitäskö käydä lounaalla vai kaljalla tänää?` ei triggeröisi tuota komentoa, koska siinä on kysymysmerkki keskellä viestiä.

**Comment by matias-kovero** [comment]
>Eli esim viesti: 
`Mitä kuuluu? Pitäskö käydä lounaalla vai kaljalla tänää?` 
ei triggeröisi tuota komentoa, koska siinä on kysymysmerkki keskellä viestiä.

Ominaisuus jakaa lauseen karusti kahtia "vai" sanan kohdalta,
`Mitä kuuluu? Pitäskö käydä lounaalla vai kaljalla tänää?`

1. `Mitä kuuluu? Pitäskö käydä lounaalla`
2. `kaljalla tänään?`
---
Ominaisuus kaipaisi kyllä pientä hienosäätöä, mutta miten?

Esim: `Hienoa! Meillä on myös paikka hakusessa. Haluatko hostata vai etitäänkö joku kerhohuoneen nurkka?`

1. `Hienoa! Meillä on myös paikka hakusessa. Haluatko hostata`
2. `etitäänkö joku kerhohuoneen nurkka?`

- Jos mahdollinen vastaus olisi yli x merkkiä -> ei vastata.
- Vastaus pilkottaisiin erikoismerkeistä, aikaisempi esimerkki menisi:

 1. `Haluatko hostata`
 2. `etitäänkö joku kerhohuoneen nurkka?`

- Vastaus sisältää erikoismerkkejä -> ei vastata.

@rennehir mikä lähestymistapa olisi paras/onko jotain uusia ehdotuksia?

**Comment by rennehir** [comment]
@matias-kovero oisko sellainen, että testais onko mitään muita välimerkkejä (. , ! ? : ; jne) viestissä. Jos niitä löytyy niin, ei triggeröisi ollenkaan.

Eli nämä esimerkkicaset ei triggeröisi ollenkaan:
- `Hienoa! Meillä on myös paikka hakusessa. Haluatko hostata vai etitäänkö joku kerhohuoneen nurkka?`
- `Mitä kuuluu? Pitäskö käydä lounaalla vai kaljalla tänää?`

Melko naiivi ratkaisu, mutta ois helppo toteuttaa ja vähentäis tuota spämmiä :)
